name:                ModalCorrespondence
version:             0.1.0.0
github:              "MinkeVerweij/ModalCorrespondence"
license:             BSD3
author:              "Minke Verweij"
maintainer:          "example@example.com"
copyright:           "2022 Minke Verweij"

ghc-options: -Wall

extra-source-files:
- README.md

build-tools:
  - alex
  - happy

synopsis: Automated Modal Correspondence
category: Logic

description: Please see the README on GitHub at <https://github.com/MinkeVerweij/ModalCorrespondence#readme>

dependencies:
- base >= 4.7 && < 5
- array
- graphviz
# - QuickCheck

library:
  source-dirs: src

tests:
  examples:
    main: test/examples.hs
    dependencies:
      - base >= 4.8 && < 5
      - hspec
      - QuickCheck
      - ModalCorrespondence
